[package]
name = "into_the_breach"
version = "0.1.0"
authors = ["Zeno <zeno@oxydyze.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34"
